sudo: required

matrix:
  include:
    - language: node_js
      node_js: "6"
      before_install:
        - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
        - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
        - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        - sudo apt-get update -qq
        - sudo apt-get install -y -qq yarn
      install: yarn install
      script: npm run lint
      env:
        name: JS linter
    - language: node_js
      node_js: "6"
      before_install:
        - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
        - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
        - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        - sudo apt-get update -qq
        - sudo apt-get install -y -qq yarn
      install: yarn install
      script: npm test
      env:
        name: JS tests
    - language: node_js
      node_js: "6"
      before_install:
        - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
        - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
        - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        - sudo apt-get update -qq
        - sudo apt-get install -y -qq yarn
      install: yarn install
      script: npm run build_test
      env:
        name: JS build test
    - language: node_js
      node_js: "6"
      before_install:
        - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
        - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
        - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        - sudo apt-get update -qq
        - sudo apt-get install -y -qq yarn
      install: yarn install
      script: npm run build_routes_test
      env:
        name: JS route building test
    - services: docker
      install: docker-compose -f travis-docker-compose.yml build
      script: docker-compose -f travis-docker-compose.yml run golang
      env:
        name: Golang test

      cache:
        directories:
          - $HOME/.yarn-cache
