sudo: required

services:
  - docker

install:
  - docker-compose -f travis-docker-compose.yml build
  - docker-compose -f travis-docker-compose.yml run watch npm install --silent


script:
  - docker-compose -f travis-docker-compose.yml run golang
  - docker-compose -f travis-docker-compose.yml run watch npm run lint
  - docker-compose -f travis-docker-compose.yml run watch npm test
  - docker-compose -f travis-docker-compose.yml run watch npm run build_test
  - docker-compose -f travis-docker-compose.yml run watch npm run build_routes_test
