sudo: required

services:
  - docker

matrix:
  include:
    - language: node_js
      node_js: "6"
      install: npm install
      script: npm run lint
    - language: node_js
      node_js: "6"
      install: npm install
      script: npm test
    - language: node_js
      node_js: "6"
      install: npm install
      script: npm run build_test
    - language: node_js
      node_js: "6"
      install: npm install
      script: npm run build_routes_test
    - services: docker
      install: docker-compose -f travis-docker-compose.yml build
      script: docker-compose -f travis-docker-compose.yml run golang

cache:
  directories:
    - $HOME/.npm
