title: Literate Crypto
email: alice.writes.wrongs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    A collection of cryptographic problems, solved in a literate
    programming style.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  aliceriot

# Build settings
markdown: kramdown
collections:
    matasano:
        output: true
